insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 1,'Eula','Lane','eula.lane@jigrormo.ye','(762) 526-5961','1954-09-13','Insurance Clerk','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 2,'Barry','Rodriquez','barry.rodriquez@zun.mm','(267) 955-5124','2013-09-13','Mortarman','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 3,'Eugenia','Selvi','eugenia.selvi@capfad.vn','(680) 368-2192','1973-08-29','Beer Coil Cleaner','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 4,'Alejandro','Miles','alejandro.miles@dec.bn','(281) 301-2039','2013-10-16','Scale Attendant','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 5,'Cora','Tesi','cora.tesi@bivo.yt','(600) 616-7955','1971-12-14','Clinical Audiologist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 6,'Marguerite','Ishii','marguerite.ishii@judbilo.gn','(882) 813-1374','1937-09-10','Parking Meter Collector','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 7,'Mildred','Jacobs','mildred.jacobs@joraf.wf','(642) 665-1763','1967-04-15','Business Unit Manager','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 8,'Gene','Goodman','gene.goodman@kem.tl','(383) 458-2132','2010-02-23','Technical Communicator','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 9,'Lettie','Bennett','lettie.bennett@odeter.bb','(769) 335-6771','1959-04-30','Correctional Officer Sergeant','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 10,'Mabel','Leach','mabel.leach@lisohuje.vi','(803) 586-8035','1946-04-06','Food Chemist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 11,'Jordan','Miccinesi','jordan.miccinesi@duod.gy','(531) 919-2280','1982-05-18','Signals Intelligence/Electronic Warfare Chief','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 12,'Marie','Parkes','marie.parkes@nowufpus.ph','(814) 667-8937','1943-03-19','Language Pathologist','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 13,'Rose','Gray','rose.gray@kagu.hr','(713) 311-8766','1958-03-18','Wildlife Officer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 14,'Garrett','Stokes','garrett.stokes@fef.bg','(381) 421-2371','2008-12-27','Bindery Machine Operator','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 15,'Barbara','Matthieu','barbara.matthieu@derwogi.jm','(940) 463-7299','1929-12-23','Instructional Aide','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 16,'Jean','Rhodes','jean.rhodes@wehovuce.gu','(777) 435-9570','1949-06-01','Clinical Psychiatrist','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 17,'Jack','Romoli','jack.romoli@zamum.bw','(517) 393-9630','1975-03-28','Mortician Investigator','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 18,'Pearl','Holden','pearl.holden@dunebuh.cr','(711) 904-3669','1949-07-23','Rod Buster Helper','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 19,'Belle','Montero','belle.montero@repiwid.si','(935) 404-4792','1932-08-15','Classroom Aide','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 20,'Olive','Molina','olive.molina@razuppa.ga','(935) 267-8492','1934-02-25','Traditional Chinese Herbalist','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 21,'Minerva','Todd','minerva.todd@kulmenim.ad','(763) 948-4815','1950-07-29','Electronic Drafter','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 22,'Bobby','Pearson','bobby.pearson@ib.kg','(238) 240-2561','2014-12-21','Vault Teller','Worker',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 23,'Larry','Ciappi','larry.ciappi@ba.lk','(410) 257-1723','1996-01-06','Fire Sprinkler Installer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 24,'Ronnie','Salucci','ronnie.salucci@tohhij.lv','(566) 726-3346','1974-07-10','Brewery Pumper','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 25,'Walter','Grossi','walter.grossi@tuvo.sa','(416) 906-7221','1987-08-28','Kitchen Chef','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 26,'Frances','Koopmans','frances.koopmans@foga.tw','(611) 712-1562','1966-10-19','Medical Esthetician','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 27,'Frances','Fujimoto','frances.fujimoto@uswuzzub.jp','(919) 887-8542','1936-03-24','Auto Tire Worker','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 28,'Olivia','Vidal','olivia.vidal@hivwerip.vc','(982) 684-7650','1933-07-02','Semi-Truck Driver','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 29,'Edna','Henry','edna.henry@gugusu.rw','(811) 931-8202','1947-05-16','Command And Control','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 30,'Lydia','Brun','lydia.brun@zedekak.md','(927) 400-3928','1929-06-28','Drywall Hanger','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 31,'Jay','Blake','jay.blake@ral.mk','(365) 345-1498','2009-07-16','Real Property Evaluator','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 32,'Isabel','Serafini','isabel.serafini@turuhu.bh','(656) 968-9869','1973-07-24','Human Performance Professor','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 33,'Rebecca','Carter','rebecca.carter@omjo.et','(739) 612-6585','1959-02-10','V/Stol Landing Signal Officer','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 34,'Maurice','Fabbrini','maurice.fabbrini@rig.bh','(485) 521-2687','1992-12-16','Air Control/Anti-Air Warfare Officer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 35,'Ollie','Turnbull','ollie.turnbull@sicewap.org','(835) 620-3330','1944-08-12','General Superintendent','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 36,'Jerry','Hopkins','jerry.hopkins@fo.mh','(211) 851-5960','2014-09-06','Child Protective Services Social Worker','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 37,'Nora','Lyons','nora.lyons@gegijap.na','(811) 311-5257','1945-06-20','Lens Grinder and Polisher','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 38,'Anne','Weiß','anne.weiß@kuvesa.pe','(843) 836-3759','1941-01-06','Civil Engineering Professor','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 39,'Louise','Gauthier','louise.gauthier@lapahu.mt','(913) 235-1856','1930-04-18','Mobile Home Servicer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 40,'Lloyd','Fani','lloyd.fani@zev.ru','(467) 487-7239','1992-03-22','Floor Refinisher','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 41,'Maud','Dunn','maud.dunn@nabeaga.ni','(724) 340-3634','1955-06-14','Senior Sales Associate','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 42,'Henry','Gigli','henry.gigli@kaot.ps','(413) 229-8428','1988-08-16','Tile Designer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 43,'Virgie','Werner','virgie.werner@tawuctuj.cf','(886) 292-9749','1941-09-25','Econometrics Professor','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 44,'Gregory','Cozzi','gregory.cozzi@eh.ru','(418) 472-1239','1994-07-19','Basketball Player','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 45,'Lucinda','Gil','lucinda.gil@fajjusuz.kr','(961) 233-3461','1934-07-10','Indirect Fire Infantryman','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 46,'Gertrude','Verbeek','gertrude.verbeek@pave.cc','(605) 226-4037','1964-07-23','Licensed Esthetician','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 47,'Mattie','Graham','mattie.graham@ispaviw.gt','(719) 765-1705','1957-05-21','Antisubmarine Warfare Intelligence Officer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 48,'Bryan','Shaw','bryan.shaw@ha.ee','(232) 228-5539','2019-01-15','Research Assistant','Manager',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 49,'Essie','Adams','essie.adams@iliat.cw','(768) 554-8377','1958-07-27','Cigar Roller','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 50,'Gary','Osborne','gary.osborne@do.ga','(311) 731-7079','2009-05-15','Customer Support Representative','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 51,'Richard','Silva','richard.silva@wi.lc','(207) 554-6244','2014-12-25','Programmer','Manager',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 52,'Dustin','Pestelli','dustin.pestelli@iwage.la','(558) 913-2855','1978-04-30','Global Engineering Manager','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 53,'Henrietta','Hilton','henrietta.hilton@joopoju.pn','(832) 759-6654','1944-02-22','Telegraph and Teletype Operator','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 54,'Francisco','Giordano','francisco.giordano@gojawu.tn','(482) 736-8079','1988-07-31','Hairpiece Stylist','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 55,'Cynthia','Sardi','cynthia.sardi@afigoh.mm','(677) 345-2680','1974-01-19','Tobacco Buyer','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 56,'Lula','Testi','lula.testi@benom.tj','(610) 374-7581','1971-11-16','Marine Steamfitter','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 57,'Bess','Lucas','bess.lucas@jevakbe.cd','(982) 583-8067','1929-04-26','Attending Anesthesiologist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 58,'Linnie','Driessen','linnie.driessen@darhow.tr','(680) 266-3167','1968-01-25','Certified Indoor Environmentalist','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 59,'Eva','Tesi','eva.tesi@dupid.cf','(611) 955-4652','1971-12-07','Land Management Forester','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 60,'Augusta','Sakai','augusta.sakai@comouc.ee','(940) 714-8088','1936-09-13','Digital Proofing and Platemaker','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 61,'Mathilda','Schwarz','mathilda.schwarz@igunisi.ao','(868) 481-5125','1942-01-07','Public Health Veterinarian','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 62,'Joe','Riley','joe.riley@pe.vu','(225) 395-2772','2017-06-17','Statement Processor','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 63,'Leon','McGee','leon.mcgee@puk.se','(365) 837-6888','2011-04-03','Computer Applications Developer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 64,'Florence','Viviani','florence.viviani@vegub.no','(606) 352-8734','1970-01-24','African History Professor','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 65,'Lee','Miceli','lee.miceli@rucwi.pf','(555) 800-7339','1982-04-29','Gastroenterology Professor','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 66,'Celia','Sodi','celia.sodi@agijit.iq','(657) 357-3671','1973-02-19','Laboratory Animal Caretaker','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 67,'Aaron','Misuri','aaron.misuri@loolu.lu','(523) 789-5485','1982-01-21','Water Pump Installer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 68,'Fanny','Parkinson','fanny.parkinson@tupwovali.cw','(766) 966-7387','1949-11-02','Orthopedic Cast Specialist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 69,'Phoebe','Vitale','phoebe.vitale@hidge.fo','(672) 613-2954','1970-03-05','Budget Coordinator','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 70,'Edith','Brennan','edith.brennan@liowci.ir','(803) 549-9387','1948-08-14','Railroad Engineer','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 71,'Jeremy','Marilli','jeremy.marilli@vesa.pf','(526) 435-1819','1984-02-17','Chief Projectionist','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 72,'Kathryn','Huet','kathryn.huet@wupikdoh.by','(937) 855-5936','1927-08-06','Telecasting Engineer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 73,'Lelia','Matsuo','lelia.matsuo@dajsiphaj.az','(960) 335-6192','1935-08-17','Drama Therapist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 74,'Virginia','Woods','virginia.woods@soofpe.ht','(735) 809-2611','1955-05-25','General Superintendent','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 75,'Sally','Aoki','sally.aoki@aruzusjas.tc','(857) 797-7918','1937-07-26','Technical Communicator','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 76,'Isabelle','de Ridder','isabelle.deridder@ufeco.in','(659) 331-1543','1963-05-12','Leisure Studies Professor','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 77,'Rosie','Murphy','rosie.murphy@uneehi.id','(759) 639-8597','1958-11-12','Air Conditioning Service Technician','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 78,'Lou','Meyer','lou.meyer@hahinaba.gm','(942) 352-4854','1929-08-07','Business Unit Manager','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 79,'Rodney','Love','rodney.love@zun.ph','(247) 867-8287','2012-12-01','Job Estimator','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 80,'Kenneth','Bianchini','kenneth.bianchini@jo.ws','(302) 793-9936','2001-11-23','Correctional Officer Sergeant','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 81,'Essie','Dietrich','essie.dietrich@goltuefo.mn','(861) 740-6628','1939-07-26','Parking Meter Collector','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 82,'Leila','Simon','leila.simon@lupuwuzo.gw','(953) 866-9992','1931-04-22','Signals Intelligence/Electronic Warfare Chief','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 83,'Eva','Pierre','eva.pierre@reduzris.ee','(915) 491-8384','1928-05-03','Clinical Psychiatrist','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 84,'Landon','Moretti','landon.moretti@pubsav.sk','(584) 909-6235','1981-08-06','Wildlife Officer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 85,'Mittie','Sardi','mittie.sardi@lullip.nf','(673) 849-4256','1974-01-14','Food Chemist','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 86,'Corey','McDaniel','corey.mcdaniel@aba.tc','(268) 208-9643','2013-03-20','Advanced Foreign Counterintelligence Specialist (Afcs)','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 87,'Hester','Stein','hester.stein@kettujwo.eu','(873) 489-6641','1940-01-11','Forest Fire Officer','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 88,'Danny','Lowe','danny.lowe@ju.sd','(243) 974-5539','2014-04-25','Catalogue Illustrator','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 89,'Lillie','Winter','lillie.winter@vioburez.vi','(816) 699-1291','1946-03-20','Knife Grinder','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 90,'Brandon','Borchi','brandon.borchi@ig.al','(319) 401-1090','2001-01-09','Neuropsychiatrist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 91,'Isaac','Bernardi','isaac.bernardi@omu.bj','(359) 691-6408','2002-06-22','Bottle Packer','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 92,'Clyde','Crawford','clyde.crawford@luw.dz','(273) 892-4646','2019-06-25','Special Education Kindergarten Teacher','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 93,'Paul','Sherman','paul.sherman@pi.cf','(304) 610-2881','2008-12-01','Commercial Art Instructor','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 94,'Craig','Russell','craig.russell@zu.nz','(237) 969-2900','2020-09-28','Ferryboat Captain','Supervisor',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 95,'John','Sutton','john.sutton@ag.ee','(207) 424-6468','2013-12-10','School Social Worker','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 96,'Francisco','Formigli','francisco.formigli@fopav.tn','(481) 661-8179','1990-11-24','Joint Terminal Attack Controller','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 97,'Gary','Baker','gary.baker@ji.cf','(212) 510-3444','2022-12-14','VP Sales','Worker',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 98,'Earl','Giovannoni','earl.giovannoni@lojet.ge','(433) 862-3076','1988-04-23','Auto Service Station Attendant','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 99,'Helen','Zanieri','helen.zanieri@ukve.tn','(619) 506-4452','1969-09-05','Healthcare Social Worker','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 100,'Agnes','Toccafondi','agnes.toccafondi@viipo.ae','(616) 688-6883','1971-09-25','Comedian','External',false)
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 1,'1395 Jigror Park','67242','Wekviwik','Ohio','Philippines')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 2,'216 Zunnij Grove','16795','Wosilleg','Colorado','Bhutan')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 3,'1016 Capfad View','59016','Ucaedaut','Missouri','Liechtenstein')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 4,'214 Decde River','19120','Uddako','Colorado','Bhutan')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 5,'1050 Bivo Way','50051','Canvorac','Montana','Macedonia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 6,'1734 Judbi Grove','88281','Igulahep','Utah','Syria')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 7,'1143 Joraf Way','54266','Peprafome','New Hampshire','Mexico')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 8,'287 Kemdol Street','19335','Ohruzi','Delaware','Burkina Faso')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 9,'1302 Odeter Circle','67913','Zudsova','North Carolina','Norfolk Island')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 10,'1563 Lisoh Square','70348','Ceksohuje','Rhode Island','Slovenia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 11,'842 Duod Lane','43191','Ladudnu','Massachusetts','Iran')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 12,'1624 Nowuf Plaza','82466','Gipwufpus','South Dakota','Sri Lanka')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 13,'1325 Kagu Loop','61311','Dedguza','North Carolina','Norway')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 14,'310 Feffo Grove','19122','Odgave','Delaware','Cameroon')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 15,'1888 Derwo Park','95026','Pahlosgi','West Virginia','Ukraine')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 16,'1500 Wehovu Boulevard','78723','Aresueba','Pennsylvania','Saudi Arabia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 17,'984 Zamum Drive','41719','Gookpaf','Missouri','Lebanon')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 18,'1497 Dune Parkway','71190','Gawnebuh','Pennsylvania','Saudi Arabia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 19,'1836 Repi Terrace','93520','Lihpiwid','Virginia','Turkmenistan')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 20,'1805 Razup Extension','93516','Lidzuppa','Virginia','Trinidad & Tobago')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 21,'1477 Kulmen Junction','77394','Zewekse','Oregon','Samoa')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 22,'191 Ibca View','03804','Lunaor','California','Belize')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 23,'569 Baaci Place','21005','Faromo','Indiana','Equatorial Guinea')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 24,'999 Tohhij Pass','46672','Vojogkiw','Missouri','Liberia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 25,'736 Tuvo Road','31690','Goborofu','Louisiana','Guadeloupe')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 26,'1153 Foga Turnpike','51161','Fapgasun','New Hampshire','Micronesia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 27,'1764 Uswuz Trail','81978','Fuswuzzub','Utah','Tanzania')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 28,'1818 Hivwe Point','99258','Oginojrip','Virginia','Tristan da Cunha')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 29,'1541 Gugu Heights','71193','Gazgusu','Rhode Island','Singapore')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 30,'1898 Zede Point','93730','Jojdekak','West Virginia','United Kingdom')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 31,'299 Ralcul Place','16514','Vipiul','Delaware','Cambodia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 32,'1018 Turuhu Court','56696','Towezedup','Missouri','Liechtenstein')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 33,'1307 Omjo Highway','63951','Lumjoda','North Carolina','North Korea')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 34,'630 Riggi Park','39542','Injari','Iowa','France')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 35,'1596 Sice Trail','74552','Mincewap','South Carolina','South Georgia & South Sandwich Islands')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 36,'197 Fodin River','02175','Gasamzit','California','Benin')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 37,'1579 Gegi Square','72121','Haggijap','South Carolina','Somalia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 38,'1668 Kuve Park','84383','Netvesa','Tennessee','St. Martin')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 39,'1882 Lapa Boulevard','91303','Febpahu','Washington','Uganda')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 40,'645 Zevvat Pass','37738','Zoisdom','Kansas','French Polynesia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 41,'1380 Nabe Terrace','62414','Jifbeaga','Ohio','Paraguay')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 42,'717 Kaot Ridge','31302','Gejuwij','Louisiana','Greenland')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 43,'1654 Tawuc View','89609','Upajuctuj','Tennessee','St. Lucia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 44,'599 Ehgad Road','21837','Fuzefo','Iowa','Falkland Islands')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 45,'1798 Fajju View','87113','Zacleunu','Vermont','Tonga')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 46,'1198 Pave Extension','50502','Dicveed','New Jersey','Morocco')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 47,'1341 Ispav Mill','61976','Duspaviw','North Dakota','Pakistan')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 48,'110 Haam Grove','03202','Kejuhib','Arizona','Ascension Island')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 49,'1317 Iliat Glen','66845','Vulmutma','North Carolina','Northern Mariana Islands')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 50,'303 Dogo Road','11163','Dakartov','Delaware','Cambodia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 51,'191 Wipir Pike','00745','Borivon','California','Belize')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 52,'923 Iwage Parkway','46891','Tugefpe','Minnesota','Kazakhstan')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 53,'1605 Joopo Avenue','84265','Mepopoju','South Carolina','South Korea')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 54,'718 Gojawu Trail','39273','Ofkotiwu','Louisiana','Greenland')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 55,'1008 Afigoh Path','57714','Atarajip','Missouri','Libya')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 56,'1052 Benom Terrace','51027','Fagnomezi','Montana','Macedonia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 57,'1902 Jevak Lane','99238','Ihelokbe','West Virginia','United Kingdom')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 58,'1128 Darhow Trail','59006','Ucatetilo','Nevada','Mauritius')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 59,'1050 Dupid Extension','51195','Fawpidba','Montana','Macedonia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 60,'1754 Como Manor','84061','Narmouc','Utah','Tajikistan')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 61,'1648 Iguni Drive','87828','Wugfinsi','South Dakota','St. Kitts & Nevis')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 62,'141 Pepal Lane','02529','Jiumne','Arkansas','Bahamas')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 63,'265 Pukvoh Point','17583','Zimopjof','Connecticut','Brunei')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 64,'1088 Vegub Plaza','50625','Cofgubgok','Nebraska','Mali')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 65,'843 Rucwi Point','45580','Sicarwit','Massachusetts','Iran')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 66,'1026 Agijit Manor','56725','Sogzeknew','Montana','Lithuania')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 67,'848 Loolu Pass','42368','Heewirar','Massachusetts','Iran')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 68,'1492 Tupwov Path','77696','Wowvossul','Pennsylvania','São Tomé and Príncipe')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 69,'1086 Hidge Highway','58251','Egikeki','Nebraska','Mali')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 70,'1516 Liow Boulevard','71344','Delowci','Pennsylvania','Serbia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 71,'807 Vesa Point','42633','Jomiwu','Maryland','Hong Kong SAR China')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 72,'1936 Wupik Plaza','94785','Motpikdoh','Wisconsin','Vanuatu')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 73,'1776 Dajsip Terrace','87013','Zadpitu','Vermont','Timor-Leste')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 74,'1381 Soof Avenue','63570','Mitofpe','Ohio','Paraguay')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 75,'1737 Aruzus Plaza','86779','Vorwowvec','Utah','Syria')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 76,'1222 Ufeco Manor','66923','Vufgamil','New Mexico','Namibia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 77,'1311 Uneehi Loop','65963','Sunuvni','North Carolina','North Korea')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 78,'1896 Hahin River','94215','Pedhinaba','West Virginia','United Arab Emirates')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 79,'232 Zunago Street','15786','Rototwu','Colorado','Bosnia & Herzegovina')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 80,'452 Joluk Way','20269','Ceujuuh','Hawaii','Costa Rica')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 81,'1697 Goltu View','86174','Varcouve','Texas','Suriname')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 82,'1862 Lupuwu Junction','96386','Vetsuwkop','Washington','U.S. Outlying Islands')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 83,'1921 Reduz Turnpike','91539','Fihduzris','West Virginia','Uruguay')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 84,'857 Pubsav Square','49490','Ulcunit','Massachusetts','Ireland')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 85,'1008 Lullip Place','58384','Ejuojtom','Missouri','Libya')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 86,'226 Abaudu Center','17800','Wucuduc','Colorado','Bosnia & Herzegovina')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 87,'1688 Kettuj Loop','88338','Ijeopumo','Texas','Sudan')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 88,'204 Junib Circle','04387','Nealidi','Colorado','Bermuda')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 89,'1564 Viobu Way','71659','Fonoburez','Rhode Island','Slovenia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 90,'469 Igfa Parkway','21920','Fucare','Hawaii','Croatia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 91,'440 Omuse River','25959','Suodozu','Hawaii','Cook Islands')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 92,'101 Luwmo Heights','08389','Ejigihoc','Arizona','Aruba')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 93,'312 Pice Ridge','10451','Cigafhec','Delaware','Cameroon')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 94,'76 Zuufa Grove','04796','Movufhe','Alaska','Antigua & Barbuda')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 95,'211 Agmo Circle','10722','Bojidis','Colorado','Bhutan')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 96,'672 Fopav Trail','39166','Odvatije','Kentucky','Gambia')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 97,'31 Jibe Ridge','01241','Degawu','Alabama','Algeria')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 98,'723 Lojet Junction','34376','Netegkir','Louisiana','Grenada')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 99,'1095 Ukve Trail','51940','Fukveura','Nebraska','Malta')
insert into sample_address(version, id,street,postal_code,city,state,country) values (1, 100,'1054 Viipo Boulevard','52658','Gomipova','Montana','Madagascar')
-- Assuming `profile_picture` is a BLOB column
INSERT INTO application_user (version, id, username, name, hashed_password, profile_picture)
VALUES 
(1, '1', 'user', 'John Normal', '$2a$10$xdbKoM48VySZqVSU/cSlVeJn0Z04XCZ7KZBjUBC00eKo5uLswyOpe', UNHEX('ffd8ffe000104a46494600010101004800480000ffe20c584943435f50524f46494c4500010100000c484c696e'));

INSERT INTO application_user (version, id, username, name, hashed_password, profile_picture)
VALUES 
(1, '2', 'admin', 'Emma Executive', '$2a$10$jpLNVNeA7Ar/ZQ2DKbKCm.MuT2ESe.Qop96jipKMq7RaUgCoQedV.', UNHEX('ffd8ffe000104a46494600010101004800480000ffe20c584943435f50524f46494c4500010100000c484c696e'));
INSERT INTO user_roles (user_id, roles) VALUES ('1', 'USER');
INSERT INTO user_roles (user_id, roles) VALUES ('2', 'USER');
INSERT INTO user_roles (user_id, roles) VALUES ('2', 'ADMIN');
